- name: Install net-tools
  yum:
    name: net-tools
    state: present
- name: Create TeamCity Group
  group:
    name: teamcity 
    state: present 
- name: Create Teamcity User
  user:
    name: teamcity 
    comment: "Team City User"
    group: teamcity 
- name: Download Teamcity Tarball
  get_url:
    url: "https://download.jetbrains.com/teamcity/TeamCity-10.0.5.tar.gz"
    dest: /tmp/TeamCity-10.0.5.tar.gz
- name: Extract Teamcity Tarball
  unarchive:
    src: /tmp/TeamCity-10.0.5.tar.gz
    dest: /opt
    remote_src: True
    creates: /opt/TeamCity
- name: Set TeamCity Directory permissions
  file:
    path: /opt/TeamCity
    recurse: yes
    owner: teamcity
    group: teamcity
- name: Set TEAMCITY_HOME system-wide 
  shell: echo export TEAM_CITY_HOME="/opt/TeamCity" > /etc/profile.d/teamcity.sh
- name: Set permissions on teamcity.sh
  file:
    path: /etc/profile.d/teamcity.sh
    mode: 0755
- name: Copy TeamCity systemd file for server
  template:
    src: templates/teamcity-server.service.j2
    dest: /etc/systemd/system/teamcity-server.service
    owner: root
    group: root 
    mode: 0755
- name: Create BuildServer jdbc folder
  file:
    path: /home/teamcity/.BuildServer/lib/jdbc
    state: directory
    owner: teamcity
    group: teamcity
- name: Download JDBC Postgres driver
  get_url:
    url: https://jdbc.postgresql.org/download/postgresql-42.0.0.jre6.jar
    dest: /home/teamcity/.BuildServer/lib/jdbc
    owner: teamcity
    group: teamcity
    mode: 0755
- name: Enable Teamcity server service
  systemd:
    name: teamcity-server
    state: started
    enabled: yes
    masked: no
    daemon_reload: yes
